########### Home Assistant ########### 
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
lovelace:
  mode: yaml
  
########### Includes ########### 
zone: !include zones.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
switch: !include switches.yaml
light: !include light.yaml
cover: !include covers.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
cloud: !include cloud.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

########### Integrations ########### 
default_config:
speedtestdotnet:
    server_id: 5803
updater:
config:
switcher_kis:
    phone_id: !secret switcher_phone_id
    device_id: !secret switcher_device_id
    device_password: !secret switcher_device_pass
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
media_player:
  - platform: androidtv
    name: Attic Streamer
    host: !secret attic_mibox_ip
  
feedreader:
  urls:
    - http://www.ynet.co.il/Integration/StoryRss2.xml
    
smartir:

zoneminder:
  - host: !secret zm_host
    ssl: true
    verify_ssl: true
    username: !secret zm_user
    password: !secret zm_pass
    
camera:
  - platform: zoneminder
stream:

climate:
  - platform: smartir
    name: Noam AC
    unique_id: noam_ac
    device_code: 1180
    controller_data: !secret broadlink_rm2_ip
    temperature_sensor: sensor.0x00158d0001b790ee_temperature
    humidity_sensor: sensor.0x00158d0001b790ee_humidity
    power_sensor: binary_sensor.noam_bedroom_ac
    
  - platform: smartir
    name: Attic AC
    unique_id: attic_ac
    device_code: 1380
    controller_data: remote.attic_broadlink_remote
    temperature_sensor: sensor.attic_broadlink_a1_temperature
    humidity_sensor: sensor.attic_broadlink_a1_humidity
    power_sensor: binary_sensor.attic_ac

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chatid_noam
      - !secret telegram_chatid_group
      - !secret telegram_chatid_diagnostics

notify:
  - name: aybeserver_telegram
    platform: telegram
    chat_id: !secret telegram_chatid_group
  - name: diagnostics_telegram
    platform: telegram
    chat_id: !secret telegram_chatid_diagnostics
  - name: noam_telegram
    platform: telegram
    chat_id: !secret telegram_chatid_noam

tts:
  - platform: google_translate
  
mqtt:
    discovery: true
    broker: 127.0.0.1  
    username: !secret mqtt_user
    password: !secret mqtt_pass
    birth_message:
        topic: 'hass/status'
        payload: 'online'
    will_message:
        topic: 'hass/status'
        payload: 'offline'


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /config/certificate/fullchain.pem
  ssl_key: /config/certificate/privkey.pem
# Discover some devices automatically
discovery:
  ignore:
   - yeelight
   
yeelight:
  devices:
    !secret light_strip_ip:
      name: Sofa Lightstrip
    
recorder:
  db_url: !secret db_link
  exclude:
    entity_globs:
      - device_tracker.192_168_*
########### Helpers(Variables) ########### 
timer:
    boiler:
        duration: '00:45:00'
        name: "Boiler"
        icon: mdi:water-boiler
input_select:
  attic_scenes:
    name: Scenes
    options:
      - Study
      - Movie
      - Chillout
      - Lights Off
    initial: Study
    icon: mdi:lightbulb-on-outline
input_boolean:
  warm_wakeup:
    name: Warm Wakeup
    initial: off
    icon: mdi:radiator
  alarm_enabled:
    name: Activate Alarm
    initial: off
    icon: mdi:alarm
  attic_climate:
    name: Climate
    initial: off
    icon: mdi:air-conditioner
  noam_sleeping:
    name: Sleep
    initial: off
    icon: mdi:bed
  plex:
    name: Plex Attic
    initial: off
  basement_light:
    name: Basement Light
input_number:
  alarm_hour:
    name: Alarm Hour
    icon: mdi:timer
    initial: 9
    min: 0
    max: 23
    step: 1
  alarm_minute:
    name: Alarm Minute
    icon: mdi:timer
    initial: 0
    min: 0
    max: 59
    step: 5
input_datetime:
    alarm_time:
        name: Alarm Time
        has_date: false
        has_time: true
        initial: '07:30:00'